// config.bin - 19:27:20 03/26/20, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	DESTRUCTNO = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class DZ_Weapons_Firearms_Winchester70 {
		units[] = {"Winchester70", "Winchester70_Black", "Winchester70_Green"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Weapons_Firearms"};
	};
};
class Mode_Safe;	// External class reference
class Mode_SemiAuto;	// External class reference
class Mode_Burst;	// External class reference
class Mode_FullAuto;	// External class reference
class OpticsInfoRifle;	// External class reference

class cfgWeapons {
	class BoltActionRifle_InnerMagazine_Base;	// External class reference
	class Winchester70_Base;
	class Winchester70;
	
	class Kol_Winchester70 : Winchester70 {
		scope = 2;
		displayName = "$STR_cfgWeapons_Winchester700";
		descriptionShort = "$STR_cfgWeapons_Winchester701";
		model = "\Kolobok_Server_Kolobok\winchester70\winchester70.p3d";
		attachments[] = {"weaponWrap", "weaponOpticsHunting", "suppressorImpro"};
		itemSize[] = {10, 3};
		hiddenSelectionsTextures[] = {"dz\weapons\firearms\winchester70\data\winchester70_CO.paa"};
		hiddenSelectionsMaterials[] = {"dz\weapons\firearms\winchester70\data\winchester70.rvmat"};
		
		class DamageSystem {
			class GlobalHealth {
				class Health {
					hitpoints = 200;
					healthLevels[] = {{1.0, {"DZ\weapons\firearms\winchester70\data\winchester70.rvmat"}}, {0.7, {"DZ\weapons\firearms\winchester70\data\winchester70.rvmat"}}, {0.5, {"DZ\weapons\firearms\winchester70\data\winchester70_damage.rvmat"}}, {0.3, {"DZ\weapons\firearms\winchester70\data\winchester70_damage.rvmat"}}, {0.0, {"DZ\weapons\firearms\winchester70\data\winchester70_destruct.rvmat"}}};
				};
			};
		};
		
		class Particles {
			class OnFire {
				class SmokeCloud {
					overrideParticle = "weapon_shot_winded_smoke";
				};
				
				class MuzzleFlash {
					overrideParticle = "weapon_shot_winch70_01";
					ignoreIfSuppressed = 1;
					illuminateWorld = 1;
					positionOffset[] = {0.1, 0, 0};
				};
			};
			
			class OnOverheating {
				shotsToStartOverheating = 1;
				maxOverheatingValue = 3;
				overheatingDecayInterval = 4;
				
				class BarrelSmoke {
					overrideParticle = "smoking_barrel_small";
				};
				
				class OpenChamberSmoke {
					onlyIfBoltIsOpen = 1;
					overrideParticle = "smoking_barrel_small";
					overridePoint = "Nabojnicestart";
				};
			};
			
			class OnBulletCasingEject {
				class ChamberSmokeRaise {
					overrideParticle = "weapon_shot_chamber_smoke_raise";
					overridePoint = "Nabojnicestart";
				};
			};
		};
	};
	
	class Winchester70_Black : Winchester70 {
		scope = 2;
		descriptionShort = "$STR_cfgWeapons_Winchester70_Black0";
		hiddenSelectionsTextures[] = {"#(argb,8,8,3)color(0.15,0.15,0.15,1.0,CO)"};
	};
	
	class Winchester70_Green : Winchester70 {
		scope = 2;
		descriptionShort = "$STR_cfgWeapons_Winchester70_Green0";
		hiddenSelectionsTextures[] = {"#(argb,8,8,3)color(0.35,0.36,0.28,1.0,CO)"};
	};
};
